<?xml version="1.0" encoding="UTF-8"?>
<!--
Consider an application in which the stock of new and used cars
held by a car dealer is to be represented in XML. The stock of
the dealer comprises zero or more cars, each of which is either a
new-car or a used-car . For a new-car , information on model
and price are recorded. For a used-car , information on
model , mileage and price are recorded, along with optional
information about the condition of the car. Elements model ,
mileage , price and condition contain text.
-->

<!DOCTYPE stock [
<!ELEMENT stock     (new-car | used-car)*>
<!ELEMENT new-car   (model, price, condition?)>
<!ELEMENT used-car  (model, price, mileage, condition?)>
<!ELEMENT model     (#PCDATA)>
<!ELEMENT price     (#PCDATA)>
<!ELEMENT mileage   (#PCDATA)>
<!ELEMENT condition (#PCDATA)*>
]>

<stock>
    <new-car>
        <model>Ford Fiesta</model>
        <price>&#163;9,500</price>
        <condition>New</condition>
    </new-car>
    <used-car>
        <model>VW New Beetle</model>
        <price>&#163;3,500</price>
        <mileage>12,000km</mileage>
        <condition>Good conditions</condition>
    </used-car>
    <new-car>
        <model>Fiat 500</model>
        <price>&#163;13,000</price>
    </new-car>
    <used-car>
        <model>Peugeot 307</model>
        <price>&#163;1,300</price>
        <mileage>102,000 km</mileage>
    </used-car>
</stock>